{% set version = "2.0.9" %}

package:
  name: bob.learn.em
  version: {{ version }}

source:
  fn: bob.learn.em-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.learn.em/bob.learn.em-{{ version }}.zip
  md5: ac2e39cd62a2c4072a83985c1e8f1445

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core >2.0.5
    - bob.io.base
    - bob.sp
    - bob.math
    - bob.learn.activation
    - bob.learn.linear
    - cmake
    - pkg-config
    - boost 1.61.*

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core >2.0.5
    - bob.io.base
    - bob.sp
    - bob.math
    - bob.learn.activation
    - bob.learn.linear
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.learn.em

  imports:
    - bob
    - bob.learn
    - bob.learn.em
    - bob.learn.em.test

  requires:
    - nose

about:
  home: http://github.com/bioidiap/bob.learn.em
  license: Modified BSD License (3-clause)
  summary: Bindings for emelaneous machines and trainers of Bob

extra:
  recipe-maintainers:
    - 183amir
